### ISSUE TITLE
Configurable delimiter

### ISSUE THREAD

**Issue by yhoiseth** [james-e-morris/csv-logger#2]
Thanks for sharing this package. Very useful.

I am working on an application that logs numbers to a CSV file. The user’s locale uses comma — `,` — as a decimal separator.

This causes problems with csv-logger, as the delimiter it writes [is also a comma](https://github.com/Morrious/csv-logger/blob/prod/src/csv_logger/csv_logger.py#L15): `msg = ','.join(map(str, msg))`

As a workaround, I monkey-patch the file to use semicolon — `;` — instead. To avoid this, it would be useful to be able to choose a custom delimiter.

I can create a pull request if you want :)

**Comment by james-e-morris** [comment]
I thought I had the delimiter as an input, but I guess not. My bad, that's a significant oversight. Working on it now.

**Comment by james-e-morris** [comment]
@yhoiseth done!

update to the latest version with `pip3 install csv-logger --upgrade`

The ReadMe has been updated and there is release info here: https://github.com/Morrious/csv-logger/releases/tag/1.3.0

**Comment by yhoiseth** [comment]
Sweet! I’ll give it a try.

**Comment by yhoiseth** [comment]
Works great. Thanks a lot :)
